### ISSUE TITLE
圖源死亡，請求修復

### ISSUE THREAD

**Issue by we684123** [HLearning/OpenCV-Python-Tutorials#1]
如題
目前確認[第5章](https://github.com/HLearning/OpenCV-Python-Tutorials/blob/master/docs/5.%20%E7%89%B9%E5%BE%81%E6%A3%80%E6%B5%8B%E5%92%8C%E6%8F%8F%E8%BF%B0/5.1.%20%E4%BA%86%E8%A7%A3%E7%89%B9%E5%BE%81.md)幾乎全部都死圖了，不確定其他章有沒有這樣
如果可以的話，請求修復一下。

**Comment by HLearning** [comment]
感谢关注， 图源来源于opencv官网， 并没有出现死图的状况， 你可以检查一下自己的网络， 是否可以请求opencv官网

**Comment by we684123** [comment]
啊 原來，3天前剛好是 opencv 官網死亡，現在恢復了。
謝謝回應
![Imgur](https://imgur.com/yEPkt0o.png)
